blueprint:
  name: Update Notifications v6.3 — relative reminders (minutes)
  description: >
    Sender påmindelser om Home Assistant updates (entities i domain 'update'),
    relativt til hvornår de blev "on". Første påmindelse kommer efter det
    valgte antal MINUTTER, og du kan valgfrit gentage med et minut-interval.
    Ignorerer updates med attributes.in_progress = true.
  domain: automation
  input:
    reminder_after_minutes:
      name: Første påmindelse efter (minutter)
      description: "Antal minutter fra update blev 'on' til første påmindelse (0 = straks)."
      default: 60
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: minutes
          mode: box

    repeat_every_minutes:
      name: Gentag hver (minutter, 0 = ingen gentagelse)
      description: "Sæt til 0 for kun én påmindelse. Brug små værdier (fx 1-5) til hurtig test."
      default: 0
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: minutes
          mode: box

    notify_devices:
      name: Enheder at notificere (mobile_app)
      description: "Vælg én eller flere telefoner/tablets (mobile_app)."
      selector:
        device:
          integration: mobile_app
          multiple: true

mode: restart
max_exceeded: silent

variables:
  _after_mins: !input reminder_after_minutes
  _repeat_mins: !input repeat_every_minutes
  _notify_devices: !input notify_devices

  # Liste over update-entities der er "due" lige nu ift. minutes-logikken
  due_updates: >-
    {% set updates = states.update
         | selectattr('state','eq','on')
         | rejectattr('attributes.in_progress','eq',true)
         | list %}
    {% set now_ts = as_timestamp(now()) %}
    {% set due = [] %}
    {% for s in updates %}
      {% set age_m = ((now_ts - as_timestamp(s.last_changed)) / 60) | int(0) %}
      {% if _after_mins <= 0 %}
        {# Første påmindelse straks når den er 'on' #}
        {% set first_due = (age_m >= 0) %}
      {% else %}
        {# Første påmindelse når alder >= _after_mins #}
        {% set first_due = (age_m >= _after_mins) %}
      {% endif %}

      {% if _repeat_mins | int(0) > 0 %}
        {# Gentagelse: efter første påmindelse, hver _repeat_mins #}
        {% set repeat_due = (age_m >= _after_mins) and ((age_m - _after_mins) % _repeat_mins == 0) %}
        {% set is_due = repeat_due %}
      {% else %}
        {# Kun én påmindelse: ram kun det MINUT hvor age_m == _after_mins #}
        {% set is_due = first_due and (age_m == _after_mins) %}
      {% endif %}

      {% if is_due %}
        {% set _ = due.append(s) %}
      {% endif %}
    {% endfor %}
    {{ due }}

  due_names: >-
    {% if due_updates | count == 0 %}
      Ingen
    {% else %}
      {{ due_updates | map(attribute='name') | list | join(', ') }}
    {% endif %}

trigger:
  # Kør hvert minut så vi kan fange præcise minut-grænser
  - id: tick
    platform: time_pattern
    minutes: "/1"

condition:
  # Kun hvis der faktisk er noget "due" netop dette minut
  - condition: template
    value_template: "{{ (due_updates | count) > 0 }}"

action:
  - variables:
      msg_title: >-
        🔔 Opdateringspåmindelse ({{ due_updates | count }})
      msg_body: >-
        Følgende opdateringer er due: {{ due_names }}.
        {% if _repeat_mins | int(0) > 0 %}
        (Første efter {{ _after_mins }} min, gentages hver {{ _repeat_mins }} min.)
        {% else %}
        (Første og eneste påmindelse {{ _after_mins }} min efter status blev 'on'.)
        {% endif %}

  # Send til valgte mobile_app-enheder
  - choose:
      - conditions: "{{ _notify_devices is defined and (_notify_devices | length) > 0 }}"
        sequence:
          - repeat:
              for_each: "{{ _notify_devices }}"
              sequence:
                - device_id: "{{ repeat.item }}"
                  domain: mobile_app
                  type: notify
                  title: "{{ msg_title }}"
                  message: "{{ msg_body }}"
                  data:
                    notification_icon: "mdi:update"

  # Fallback: persistent notification i HA
  - service: persistent_notification.create
    data:
      title: "{{ msg_title }}"
      message: "{{ msg_body }}"
