blueprint:
  name: "Update Notifications (V6-Plus — multi-device, manual run, backup, core check, diagnostics)"
  description: >
    Notifikationer for update.*-enheder med Install/Skip actions (Android/iOS).
    Virker ved manuel kørsel (opsummer nu), understøtter flere mobile_app-enheder,
    valgfri backup før install, Core config-check, og diagnose-log til fejlfinding.
  domain: automation
  source_url: https://example.invalid/bukart/update_notifications_v6_plus.yaml

  input:
    update_entities:
      name: Update entities
      description: Vælg de update.* enheder der skal overvåges
      selector:
        entity:
          domain: update
          multiple: true

    notify_devices:
      name: Devices Notified (1+)
      description: Vælg én eller flere mobile_app-enheder (telefoner) som skal modtage notifikationer
      default: []
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: true

    send_to_ha:
      name: Også som HA persistent notification
      default: false
      selector:
        boolean: {}

    only_after:
      name: Kun efter (valgfrit)
      selector:
        time: {}
      default: "00:00:00"

    only_before:
      name: Kun før (valgfrit)
      selector:
        time: {}
      default: "23:59:59"

    reminder_hours:
      name: Timebaseret påmindelse (0 = fra)
      description: Hver N. time sendes en opsummering for enheder der stadig er "on"
      default: 0
      selector:
        number:
          min: 0
          max: 48
          step: 1
          mode: slider
          unit_of_measurement: h

    backup_before_install:
      name: Backup før install
      description: Kør backup.create før update.install (hvis understøttet)
      default: false
      selector:
        boolean: {}

    core_check_config:
      name: Kør Core config-check efter install-start
      description: Kald homeassistant.check_config og log resultat (kræver system_log)
      default: false
      selector:
        boolean: {}

    include_changelog_link:
      name: Medtag changelog/link hvis tilgængelig
      description: Hvis entity har release_url/relaterede attributter, tilføjes knap/URL
      default: true
      selector:
        boolean: {}

    # — Diagnose-logging —
    diag_enable:
      name: Diagnose-log (aktivér)
      description: Skriv detaljer til systemlog/logbook og (valgfrit) fire et custom event
      default: true
      selector:
        boolean: {}

    diag_level:
      name: Diagnose log-level
      default: "info"
      selector:
        select:
          options: ["debug","info","warning","error","critical"]
          mode: dropdown

    diag_fire_event:
      name: Fire diag event (diagnostic_update_blueprint)
      default: false
      selector:
        boolean: {}

mode: parallel
max: 100

# —————————————————————————————————————————
# Variables
# —————————————————————————————————————————
variables:
  _update_entities: !input update_entities
  _send_to_ha: !input send_to_ha
  _only_after: !input only_after
  _only_before: !input only_before
  _reminder_hours: !input reminder_hours
  _backup_before_install: !input backup_before_install
  _core_check_config: !input core_check_config
  _include_changelog_link: !input include_changelog_link
  _diag_enable: !input diag_enable
  _diag_level: !input diag_level
  _diag_fire_event: !input diag_fire_event

  # Alle updates der pt. er 'on' og ikke kører (in_progress != true)
  updates_on: >-
    {{
      (_update_entities
        | select('in', states.update
          | selectattr('state','eq','on')
          | rejectattr('attributes.in_progress','eq',true)
          | map(attribute='entity_id') | list)
        | list)
    }}

# —————————————————————————————————————————
# Triggers
# —————————————————————————————————————————
trigger:
  - id: new
    platform: state
    entity_id: !input update_entities
    to: "on"

  - id: started
    platform: state
    entity_id: !input update_entities
    attribute: in_progress
    from: false
    to: true

  - id: done
    platform: state
    entity_id: !input update_entities
    from: "on"
    to: "off"

  - id: install
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: install-update

  - id: install_ios
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      actionName: install-update

  - id: skip
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: skip-update

  - id: skip_ios
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      actionName: skip-update

  - id: sticky_ios
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: URI

  - id: hourly
    platform: time_pattern
    minutes: "/5"
    enabled: "{{ (_reminder_hours | int(0)) > 0 }}"

condition: []

# —————————————————————————————————————————
# Actions
# —————————————————————————————————————————
action:
  - choose:

      # — 0) Diagnose helper —
      - conditions: "{{ false }}"
        sequence: &DIAG_HELPER
          - if: "{{ _diag_enable }}"
            then:
              - service: system_log.write
                data:
                  level: "{{ _diag_level }}"
                  logger: "blueprint.update_v6_plus"
                  message: "{{ diag_message | default('') }}"
              - service: logbook.log
                data:
                  name: "Update V6-Plus"
                  message: "{{ diag_message | default('') }}"
                  domain: automation
              - if: "{{ _diag_fire_event }}"
                then:
                  - event: diagnostic_update_blueprint
                    event_data:
                      message: "{{ diag_message | default('') }}"
                      context:
                        trigger_id: "{{ trigger.id if trigger is defined else 'manual' }}"
                        entity_id: "{{ entity_id | default('') }}"
                        time: "{{ now() }}"
                        updates_on: "{{ updates_on }}"

      # — 1)
